services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  ai-chat-app:
    build: .
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
